apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  labels: 
    env: prod
    type: local
    app: pgadmin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data-pgadmin
