---
- name: k3s
  hosts: all
  become: true
  tasks:
    - name: récupérer le fichier k3s
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/vagrant/k3s.yaml
        flat: yes

    - name: Remplacer l'adresse IP du serveur API Kubernetes
      replace:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: 'https://10\.0\.2\.15:6443'
        replace: "https://{{ ansible_default_ipv4.address }}"

    - name: Create Kubernetes directory on client if it doesn't exist
      file:
        path: /home/vagrant/kubernetes
        state: directory

    - name: Synchronize Kubernetes directory from controller to client
      synchronize:
        src: /home/vagrant/datascientest/kubernetes/
        dest: /home/vagrant/kubernetes
        recursive: yes

    - name: Ensure the Kubernetes config file is accessible
      file:
        path: /etc/rancher/k3s/k3s.yaml
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Exécuter kubectl apply -k dans le répertoire Kubernetes
      command: /usr/local/bin/kubectl apply -k /home/vagrant/kubernetes
#      args:
#        chdir: /home/vagrant/datascientest/kubernetes

  handlers:
    - name: redémarrer k3s
      service:
        name: k3s
        state: restarted

